#!/bin/bash

function showHelp() {
    echo "Usage:"
    echo "      ./public -h|--help"
    echo "      ./public [home|photo|blog]: 发布指定工程"
    exit
}

function publish() {
    pushd $1
    info=`git st|grep "nothing to commit"`
    if [ "$info" = "" ];then
        echo "请先提交修改后在发布"
        exit
    fi
    # 先更新
    git pl
    mv node_modules ../public 2>/dev/null
    mv package.json ../public 2>/dev/null
    info=`git br|grep "gh-pages"`
    if [ "$info" = "" ];then
        git copage
    else
        git co gh-pages
        git plpage
    fi
    git co master
    # 打包
    mv ../public/node_modules .
    mv ../public/package.json .
    rm -fr ../public/build
    npm run build
    if [ $? -ne 0 ]; then
        exit
    fi
    mv build ../public
    mv node_modules ../public
    mv package.json ../public
    # 发布
    git co gh-pages 2>/dev/null
    v=`git lg -1|sed 's/.*发布//'|sed 's/版本.*//'|sed 's/\.//g'`
    t=`echo $v|grep '^\d\{3\}$'`
    if [ "$t" = "" ];then
        v="99"
        git co -b gh-pages
    fi
    let v=v+1
    v="发布${v:0:1}.${v:1:1}.${v:2:1}版本"
    rm -fr *
    mv ../public/build/$1/* .
    git add .
    git ci -m "$v"
    git pupage
    git co master
    rm -fr ../public/build
    popd
}

if [ "$1" = "-h" -o "$1" = "--help" ];then
    showHelp
elif [ "$1" = "home" -o "$1" = "photo" -o "$1" = "blog" ];then
    publish "$1"
else
    showHelp
fi
