#!/bin/bash

function showHelp() {
    echo "Usage:"
    echo "      ./publish -h|--help"
    echo "      ./publish [home|personal|photo|blog]: 发布指定工程"
    exit
}

function publish() {
    pushd $1
    info=`git st|grep "nothing to commit"`
    if [ "$info" = "" ];then
        echo "请先提交修改后在发布"
        exit
    fi
    # 先更新
    git pl
    if [ "$1" = "photo" ];then
        mv static/photo ../tools/photo
        mv ../tools/dist static/photo
    fi
    # 打包
    mv ../shared/node_modules .
    mv ../shared/package.json .
    rm -fr ../shared/build
    npm run build
    ret=$?
    if [ "$1" = "photo" ];then
        mv static/photo ../tools/dist
        mv ../tools/photo static/photo
    fi
    if [ $ret -ne 0 ]; then
        exit
    fi
    mv build ../shared
    mv node_modules ../shared
    mv package.json ../shared
    # 发布
    info=`git br|grep "gh-pages"`
    if [ "$info" = "" ];then
        git copage
    else
        git co gh-pages
        git plpage
    fi
    git lg
    v=`git lg -1|sed 's/.*发布//'|sed 's/版本.*//'|sed 's/\.//g'`
    t=`echo $v|grep '^\d\{3\}$'`
    if [ "$t" = "" ];then
        v="99"
        git co -b gh-pages
    fi
    let v=v+1
    v="发布${v:0:1}.${v:1:1}.${v:2:1}版本"
    echo ""
    echo $v
    rm -fr *
    mv ../shared/build/$1/* .
    git add .
    git ci "$v"
    git pupage
    git co master
    rm -fr ../shared/build
    popd
}

if [ "$1" = "-h" -o "$1" = "--help" ];then
    showHelp
elif [ "$1" = "home" -o "$1" = "xx" -o "$1" = "photo" -o "$1" = "blog" ];then
    publish "$1"
else
    showHelp
fi
