#!/bin/bash

function showHelp() {
    echo "Usage:"
    echo "      ./update -h|--help"
    echo "      ./update [home|personal|photo|blog]: 为空则更新所有工程，否则更新指定工程"
    exit
}

function updateProject() {
    pushd $1
    info=`git st|grep "nothing to commit"`
    if [ "$info" = "" ];then
        echo "请先处理修改后再更新"
        exit
    fi
    git pl
    mv node_modules ../public 2>/dev/null
    mv package.json ../public 2>/dev/null
    info=`git br|grep "gh-pages"`
    if [ "$info" = "" ];then
        git copage
    else
        git co gh-pages
        git plpage
    fi
    git co master
    popd
}

function update() {
    if [ "$1" = "" ];then
        updateProject home
        updateProject personal
        updateProject photo
        updateProject blog
    else
        updateProject "$1"
    fi
}

if [ "$1" = "-h" -o "$1" = "--help" ];then
    showHelp
elif [ "$1" = "" -o "$1" = "home" -o "$1" = "personal" -o "$1" = "photo" -o "$1" = "blog" ];then
    update "$1"
else
    showHelp
fi
