#!/usr/bin/env node

const fs = require('fs-extra');
const path = require('path');
const moment = require('moment');
const args = process.argv.slice(2);
const root = `/Users/whxx/test/data/Camera`;

if (!args[1] || args[0] === '-h' || args[0] === '--help') {
    console.log('xphoto srcDir distDir');
    console.log(`       root=${root}`);
    process.exit(0);
}

const srcDir = `${root}/${args[0]}`;
const distDir = `${root}/${args[1]}`;


fs.emptyDirSync(distDir);
fs.readdirSync(srcDir).forEach(file=>{
    const list = file.split('_');
    if (list[0] === 'IMG' && list[1].length === 8) {
        const date = moment(list[1], 'YYYYMMDD');
        const distPath = `${distDir}/${date.format('YYYY')}/${date.format('YYYY-MM-DD')}`;
        console.log("copy", file);
        fs.ensureDirSync(distPath);
        fs.copySync(`${srcDir}/${file}`, `${distPath}/${file}`);
    }
});
